sonar.projectKey=pakiapps-fe
sonar.projectName=PakiApps Frontend
sonar.sourceEncoding=UTF-8
sonar.sources=pakipark/src,pakiship/src
sonar.tests=pakipark/tests,pakiship/tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.expo/**,**/coverage/**,**/dist/**
